# Generated by Django 5.2.3 on 2025-07-08 05:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.BigIntegerField(blank=True, max_length=15, null=True)),
                ('role', models.CharField(max_length=50)),
                ('points', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('publisher', models.CharField(max_length=120)),
                ('app_logo', models.ImageField(blank=True, null=True, upload_to='app_logos/')),
                ('points', models.IntegerField()),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.customuser')),
            ],
        ),

        migrations.CreateModel(
            name='UserApps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(blank=False, null=False, on_delete=django.db.models.deletion.CASCADE, to='myapp.customuser')),
                ('app', models.ForeignKey(blank=False, null=False,on_delete=models.CASCADE, to='myapp.app')),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('screenshots', models.ImageField(blank=False, null=False, upload_to='screenshots/')),
                
                
            ],
        ),
    ]
